apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetport: 80
    selector:
#labels from the resultapp-pod.yml
      name: result-app-pod
      app: demo-voting-app
